// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAL676EGCMvO6LyJHtb6UX8nSQj8JopOKE',
    appId: '1:396705769949:web:1c6dfb5e7e50271d0b6e34',
    messagingSenderId: '396705769949',
    projectId: 'ruthere-32590',
    authDomain: 'ruthere-32590.firebaseapp.com',
    storageBucket: 'ruthere-32590.firebasestorage.app',
    measurementId: 'G-D5GELBBTYK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCNSah37ppOnJCa1s2vUvCrZ8sC8v2GVk',
    appId: '1:396705769949:android:9b604ed6ec3847ee0b6e34',
    messagingSenderId: '396705769949',
    projectId: 'ruthere-32590',
    storageBucket: 'ruthere-32590.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhn0CNp3iPrEHlTdBEr_cKAHbv_i3ALr8',
    appId: '1:396705769949:ios:f195d01ee7bb3b000b6e34',
    messagingSenderId: '396705769949',
    projectId: 'ruthere-32590',
    storageBucket: 'ruthere-32590.firebasestorage.app',
    iosBundleId: 'com.ruthere.ruthere',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhn0CNp3iPrEHlTdBEr_cKAHbv_i3ALr8',
    appId: '1:396705769949:ios:f195d01ee7bb3b000b6e34',
    messagingSenderId: '396705769949',
    projectId: 'ruthere-32590',
    storageBucket: 'ruthere-32590.firebasestorage.app',
    iosBundleId: 'com.ruthere.ruthere',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAL676EGCMvO6LyJHtb6UX8nSQj8JopOKE',
    appId: '1:396705769949:web:2bc823f9c5788cc30b6e34',
    messagingSenderId: '396705769949',
    projectId: 'ruthere-32590',
    authDomain: 'ruthere-32590.firebaseapp.com',
    storageBucket: 'ruthere-32590.firebasestorage.app',
    measurementId: 'G-ZZ8L5GBV16',
  );
}
